---
- name: Ping all non-ansible group hosts
  hosts: all:!ansible
  gather_facts: true

  tasks:
    - name: Ping Linux/Unix hosts
      ping:
      when: ansible_os_family is defined and ansible_os_family != "Windows"

    - name: Ping Windows hosts
      win_ping:
      when: ansible_os_family == "Windows"
