---
- name: Configure Wazuh Manager with updated ossec.conf
  hosts: linux:!wazuh
  become: yes
  tasks:
    - name: Ensure curl is installed
      apt:
        name: curl
        state: present
        update_cache: yes

    - name: Download ossec.conf to /var/ossec/etc/ossec.conf
      ansible.builtin.command:
        cmd: >
          sudo curl -o /var/ossec/etc/ossec.conf https://raw.githubusercontent.com/MaltheOlsen/Installation/be4b940cfa36d09b27e26e3fedac830b78375a75/Wazuh/ossec.conf
      register: download_result

    - name: Restart wazuh-manager
      ansible.builtin.systemd:
        name: wazuh-manager
        state: restarted
      when: download_result is changed
