---
- name: Install Wazuh Agent
  hosts: '{{ Host }}'
  become: yes

  tasks:
    - name: Check if Wazuh Agent is already installed
      shell: dpkg-query -W -f='${Status}' wazuh-agent | grep "install ok installed"
      ignore_errors: true
      register: wazuh_agent_installed

    - name: Install Wazuh Agent if not installed
      when: wazuh_agent_installed.rc != 0
      block:
        - name: Import Wazuh GPG key
          shell: curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg
          register: import_key_result

        - name: Add Wazuh repository
          shell: echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" | tee /etc/apt/sources.list.d/wazuh.list
          register: add_repo_result

        - name: Update package list
          shell: apt-get update
          register: update_result

        - name: Install Wazuh Agent
          shell: WAZUH_MANAGER="172.30.2.148" apt-get install -y wazuh-agent
          register: install_result

        - name: Verify Wazuh Agent installation
          fail:
            msg: "Failed to install Wazuh Agent. Please check the repository or installation process."
          when: install_result.rc != 0

    - name: Check if Wazuh Agent is running
      command: systemctl is-active wazuh-agent
      register: wazuh_agent_status
      ignore_errors: true

    - name: Start Wazuh Agent if not running
      command: systemctl start wazuh-agent
      when: wazuh_agent_status.stdout != "active"
      ignore_errors: true
