- name: Install Qemu Guest Agent
  become: yes
  hosts: '{{ Host }}'
  gather_facts: true
  tasks:
    - name: Update all installed packages
      ansible.builtin.apt:
        update_cache: yes
    - name: Install Qemu Guest Agent on Proxmox VMs
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
      when: ansible_distribution == "Ubuntu"
    - name: pause
      pause:
        seconds: 10
    - name: Start Qemu Guest Agent for Proxmox VM
      ansible.builtin.systemd:
        name: qemu-guest-agent
        enabled: true
        state: started
        daemon_reload: yes
      when: ansible_distribution == "Ubuntu"

    # after this, enabled the agent in the VM's options in proxmox,
    # to activate the service. A shutdown may be required first,
    # and the VM started again afterwards.
